services:
  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: farma-backend
    volumes:
      - ./backend:/var/www
    networks:
      - farma-network

  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    container_name: farma-webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - farma-network
    depends_on:
      - backend

  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend/farmacia-vue
      dockerfile: Dockerfile
    container_name: farma-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/farmacia-vue:/app
      - /app/node_modules
    networks:
      - farma-network
    environment:
      - VITE_API_URL=http://localhost:8001/api

networks:
  farma-network:
    driver: bridge
