services:
  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: farma-backend
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=farma_online
      - DB_USERNAME=farma_user
      - DB_PASSWORD=farma_password
    depends_on:
      - db
    networks:
      - farma-network

  # Base de Datos PostgreSQL
  db:
    image: postgres:alpine
    container_name: farma-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=farma_online
      - POSTGRES_USER=farma_user
      - POSTGRES_PASSWORD=farma_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farma-network

  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend/farmacia-vue
      dockerfile: Dockerfile
    container_name: farma-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/farmacia-vue:/app
      - /app/node_modules
    networks:
      - farma-network
    environment:
      - VITE_API_URL=http://localhost:8001/api

networks:
  farma-network:
    driver: bridge

volumes:
  postgres_data:
